# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Create pre-signing release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: GitHub release tag for the presgining release
        required: true
        type: string
      release_branch:
        description: Name of the release branch to create
        required: true
        type: string
      release_notes:
        description: GitHub release notes
        required: true
        type: string
      release_title:
        description: GitHub release title
        required: true
        type: string
      artifact_perso:
        description: Release the `perso` artifact?
        type: boolean
        default: true
      artifact_rom_ext:
        description: Release the `rom_ext` artifact?
        type: boolean
        default: true
      ot_repo:
        description: Opentitan repository to checkout
        type: string
        default: lowRISC/opentitan
      ot_ref:
        description: Git branch or commit hash to checkout (opentitan)
        type: string
        default: earlgrey_1.0.0

jobs:
  release:
    permissions:
      # Necessary permission to create a release:
      contents: write
    # Note: use the same runner as OpenTitan (see below).
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (ot-sku)
        uses: actions/checkout@v6
        with:
          path: ot-sku

      # Also checkout OT repository
      - name: Checkout (opentitan)
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.ot_repo }}
          ref: ${{ inputs.ot_ref }}
          fetch-depth: 0 # Bitstream cache requires all commits.
          path: opentitan

      # Install system dependencies from OpenTitan. Those are setup for Ubuntu 22.04.
      - name: Install system dependencies
        run: |
          sudo apt update
          grep '^[^#]' apt-requirements.txt | xargs sudo apt install -y
        working-directory: opentitan

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_OPTS=("--gha-console")
          # Increase verbosity when running with debug logging.
          if [[ "${ACTIONS_STEP_DEBUG:-}" == "true" ]]; then
            RELEASE_OPTS+=("--verbose")
          fi
          # Select artifacts to build
          if [ "${{ inputs.artifact_rom_ext && 'true' || 'false' }}" == "true" ]
          then
            RELEASE_OPTS+=("--release-artifacts" "rom_ext")
          fi
          if [ "${{ inputs.artifact_perso && 'true' || 'false' }}" == "true" ]
          then
            RELEASE_OPTS+=("--release-artifacts" "perso")
          fi
          ot-sku/scripts/release.py \
            --pre-sign \
            ${RELEASE_OPTS[@]} \
            --ot-repo opentitan \
            --release-branch "${{ inputs.release_branch }}" \
            --release-title "${{ inputs.release_title }}" \
            --release-notes "${{ inputs.release_notes }}" \
            "${{ inputs.release_tag }}"
