# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Create post-signing release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: GitHub release tag
        required: true
        type: string
      ot_repo:
        description: Opentitan repository to checkout
        type: string
        default: lowRISC/opentitan
      ot_ref:
        description: Git branch or commit hash to checkout (opentitan)
        type: string
        default: earlgrey_1.0.0

jobs:
  release:
    permissions:
      # Necessary permission to create a release:
      contents: write
      pull-requests: write
    # Note: use the same runner as OpenTitan (see below).
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (ot-sku)
        uses: actions/checkout@v6
        with:
          # We checkout the release branch.
          ref: ${{ inputs.release_tag }}
          path: ot-sku

      # Also checkout OT repository
      - name: Checkout (opentitan)
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.ot_repo }}
          ref: ${{ inputs.ot_ref }}
          fetch-depth: 0 # Bitstream cache requires all commits.
          path: opentitan

      # Install system dependencies from OpenTitan. Those are setup for Ubuntu 22.04.
      - name: Install system dependencies
        run: |
          sudo apt update
          grep '^[^#]' apt-requirements.txt | xargs sudo apt install -y
        working-directory: opentitan

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Sanity check to warn the user if not running the release flow from the release branch.
          if [ "$GITHUB_REF_NAME" != "${{ inputs.release_tag }}" ]
          then
            echo "::warning::You are running the release flow from branch $GITHUB_REF_NAME instead of the release branch ${{ inputs.release_tag }}, this can lead to unexpected results"
          fi
          RELEASE_OPTS=("--gha-console")
          # Increase verbosity when running with debug logging.
          if [[ "${ACTIONS_STEP_DEBUG:-}" == "true" ]]; then
            RELEASE_OPTS+=("--verbose")
          fi
          ot-sku/scripts/release.py \
            ${RELEASE_OPTS[@]} \
            --post-sign \
            --ot-repo opentitan \
            "${{ inputs.release_tag }}"
