# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Important note:
# this workflow is typically ran twice: the first time for a
# pre-signing release and a second time for post-signing release.
# To avoid user errors and enforce reproducibility, this file is
# set up for a pre-signing workflow in the main branch and is
# MODIFIED by the flow itself in release branches so that it becomes
# set up for a post-sigining release. This is done by changing the
# inputs parameters below. The anchors (<<< ANCHOR >>>) must not
# be removed, they are used to locate lines to change.

name: Create a release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: GitHub release tag
        required: true
        type: string
      release_type:
        description: Release type
        required: true
        type: choice
        options:
          - pre-sign
          - post-sign
        default: post-sign # <<< RELEASE_TYPE >>>
      release_branch:
        description: Name of the release branch to create/update
        required: true
        type: string
        default: release_test_3 # <<< RELEASE_BRANCH >>>
      release_notes:
        description: GitHub release notes
        required: true
        type: string
      release_title:
        description: GitHub release title
        required: true
        type: string
      artifact_perso:
        description: Release the `perso` artifact?
        type: boolean
        default: true # <<< ARTIFACT_PERSO >>>
      artifact_rom_ext:
        description: Release the `rom_ext` artifact?
        type: boolean
        default: false # <<< ARTIFACT_ROM_EXT >>>
      ot_repo:
        description: Opentitan repository to checkout
        type: string
        default: pamaury/opentitan # <<< OT_REPO >>>
      ot_ref:
        description: Git branch or commit hash to checkout (opentitan)
        type: string
        default: sku-extra # <<< OT_REF >>>

jobs:
  release:
    # Note: use the same runner as OpenTitan (see below).
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout (ot-sku)
        uses: actions/checkout@v6
        with:
          path: ot-sku

      # Also checkout OT repository
      - name: Checkout (opentitan)
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.ot_repo }}
          ref: ${{ inputs.ot_ref }}
          fetch-depth: 0 # Bitstream cache requires all commits.
          path: opentitan

      # Install system dependencies from OpenTitan. Those are setup for Ubuntu 22.04.
      - name: Install system dependencies
        run: |
          sudo apt update
          grep '^[^#]' apt-requirements.txt | xargs sudo apt install -y
        working-directory: opentitan

      - name: Create release
        env:
          # TODO document
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          RELEASE_OPTS=("--gha-console")
          ARTIFACT_PERSO="${{ inputs.artifact_perso && 'true' || 'false' }}"
          ARTIFACT_ROM_EXT="${{ inputs.artifact_rom_ext && 'true' || 'false' }}"
          # Increase verbosity when running with debug logging.
          if [[ "${ACTIONS_STEP_DEBUG:-}" == "true" ]]; then
            RELEASE_OPTS+=("--verbose")
          fi
          # Select artifacts to build
          if [ "$ARTIFACT_ROM_EXT" == "true" ]
          then
            RELEASE_OPTS+=("--release-artifacts" "rom_ext")
          fi
          if [ "$ARTIFACT_PERSO" == "true" ]
          then
            RELEASE_OPTS+=("--release-artifacts" "perso")
          fi
          if [[ "${{ inputs.release_type}}" == "pre-sign" ]]; then
            RELEASE_OPTS+=("--pre-sign")
            # Modify the release flow
            RELEASE_OPTS+=(
                "--edit-workflow"
                "RELEASE_TYPE=post-sign"
                "--edit-workflow"
                "RELEASE_BRANCH=${{ inputs.release_branch }}"
                "--edit-workflow"
                "OT_REPO=${{ inputs.ot_repo }}"
                "--edit-workflow"
                "OT_REF=${{ inputs.ot_ref }}"
                "--edit-workflow"
                "ARTIFACT_PERSO=$ARTIFACT_PERSO"
                "--edit-workflow"
                "ARTIFACT_ROM_EXT=$ARTIFACT_ROM_EXT"
            )

          elif [[ "${{ inputs.release_type}}" == "post-sign" ]]; then
            RELEASE_OPTS+=("--post-sign")
          else
            print "::error::invalid release type '${{ inputs.release_type}}'"
            exit 1
          fi
          ot-sku/scripts/release.py \
            ${RELEASE_OPTS[@]} \
            --ot-repo opentitan \
            --release-branch "${{ inputs.release_branch }}" \
            --release-title "${{ inputs.release_title }}" \
            --release-notes "${{ inputs.release_notes }}" \
            "${{ inputs.release_tag }}"
